In [3]:
#Import the Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
#Import the Dataset
df= pd.read_csv("cars_dataset.csv")

Columns (Features)

buying: Price of the car (e.g., vhigh = very high, high, med, low).
maint: Maintenance cost (e.g., vhigh = very high, high, med, low).
doors: Number of doors (e.g., two, three, four, or 5-more).
persons: Capacity in terms of persons to carry (e.g., two, four, more).
lug_boot: Size of luggage boot (e.g., small, med, big).
safety: Estimated safety of the car (e.g., low, med, high).

Target Column:
car: Class of the car, which is the evaluation result (e.g., unacc = unacceptable, acc = acceptable, good, vgood).

In [5]:
df.head()

buying  maint doors persons lug_boot safety    car
0  vhigh  vhigh   two     two    small    low  unacc
1  vhigh  vhigh   two     two    small    med  unacc
2  vhigh  vhigh   two     two    small   high  unacc
3  vhigh  vhigh   two     two      med    low  unacc
4  vhigh  vhigh   two     two      med    med  unacc

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   doors     1728 non-null   object
 3   persons   1728 non-null   object
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   car       1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [8]:
X = df.iloc[:,:-1].values
y = df.iloc[:, -1].values

In [9]:
#list all the string value and convert them in to int values!!
#Note we are doing only labelencoder 
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
X[:, 0] = labelencoder.fit_transform(X[:, 0])
X[:, 1] = labelencoder.fit_transform(X[:, 1])
X[:, 2] = labelencoder.fit_transform(X[:, 2])
X[:, 3] = labelencoder.fit_transform(X[:, 3])
X[:, 4] = labelencoder.fit_transform(X[:, 4])
X[:, 5] = labelencoder.fit_transform(X[:, 5])
     

In [10]:
#Feature scaling the independent variable
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

In [11]:
#Splitting the data into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)


C (Regularization Parameter):
Controls the trade-off between achieving a low error on the training data and minimizing the margin.

kernel:

linear: For linearly separable data.
poly: Polynomial kernel.
rbf: Radial Basis Function (default, suitable for non-linear data).
sigmoid: Sigmoid kernel.
    
degree:
Degree of the polynomial kernel (used only with poly).


In [13]:
#SVM Classification model
from sklearn.svm import SVC
classifier = SVC(C = 10.0, kernel = "linear",decision_function_shape='ovr')
classifier.fit(X_train, y_train)


SVC(C=10.0, kernel='linear')

In [14]:
#Predicting the output for our SGD Linear Model with the test set
y_pred = classifier.predict(X_test)
y_pred

array(['unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'acc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 

In [15]:
#evaluating our model.
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
acc_train = accuracy_score(y_train, classifier.predict(X_train))

f1_train = f1_score(y_train, classifier.predict(X_train), average= 'weighted')

print("Traing set results")
print("ACCURACY for train set",acc_train)


print("F1 SCORE for train set",f1_train)

Traing set results
ACCURACY for train set 0.7369727047146402
F1 SCORE for train set 0.6643775043026294


In [16]:
#evaluate our test set
acc_test = accuracy_score(y_test, y_pred)
f1_test = f1_score(y_test, y_pred, average= 'weighted')

print("Test set results")
print("ACCURACY for test set",acc_test)
print("F1 SCORE for test set",f1_test)

Test set results
ACCURACY for test set 0.7167630057803468
F1 SCORE for test set 0.6341355089951095


In [17]:
from sklearn.metrics import confusion_matrix



In [18]:
#Confusion Matrix 
cm = confusion_matrix(y_test,y_pred)


In [19]:
print(cm)

[[ 17   0 102   0]
 [  1   0  17   0]
 [  5   0 355   0]
 [ 12   0  10   0]]


In [22]:
# Predict and evaluate
y_pred = classifier.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))


Accuracy: 0.7167630057803468


In [28]:
from sklearn.metrics import classification_report, accuracy_score
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         acc       0.49      0.14      0.22       119
        good       0.00      0.00      0.00        18
       unacc       0.73      0.99      0.84       360
       vgood       0.00      0.00      0.00        22

    accuracy                           0.72       519
   macro avg       0.30      0.28      0.27       519
weighted avg       0.62      0.72      0.63       519



C:\Users\Welcome\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Welcome\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Welcome\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
